name: Close issue when status is set to completed
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  project_card:
    types: [edited]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The id of your project card is ${{ github.event.project_card.id }}"
      - run: echo "🔎 The state of your issue is ${{ github.event.project_card.state }}"
